version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      PGTZ: UTC
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
